name: Trivy

on:
  pull_request:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# set empty default permissions and define them explicitly in each job for security
permissions: {}

jobs:

  trivy-dockerfile-lint:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    permissions:
      contents: read # to checkout repository and access Dockerfile for security scanning
      security-events: write # to upload SARIF results to GitHub security dashboard (github/codeql-action)

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Run Trivy Dockerfile Lint
        uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8 # v0.33.1
        with:
          scan-type: 'config'
          scan-ref: 'Dockerfile'
          format: 'sarif'
          output: 'trivy-dockerfile-lint-results.sarif'
          severity: 'CRITICAL,HIGH,MEDIUM'
          exit-code: '0'
          ignore-unfixed: false

      - name: Upload Trivy Dockerfile Lint results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@cdefb33c0f6224e58673d9004f47f7cb3e328b89 # v4.31.10
        if: always()
        with:
          sarif_file: 'trivy-dockerfile-lint-results.sarif'
          category: 'trivy-dockerfile-lint'

  trivy-image-scan:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    permissions:
      contents: read # to checkout repository and build Docker image for security scanning
      security-events: write # to upload SARIF results to GitHub security dashboard (github/codeql-action)

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Build Docker image for scanning
        run: docker build -t docker-image:${{ github.sha }} .

      - name: Run Trivy vulnerability scanner on Docker image
        uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8 # v0.33.1
        with:
          scan-type: 'image'
          image-ref: 'docker-image:${{ github.sha }}'
          format: 'sarif'
          output: 'trivy-image-vuln-scan-results.sarif'
          severity: 'CRITICAL,HIGH,MEDIUM'
          exit-code: '0'
          ignore-unfixed: false

      - name: Upload Trivy image results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@cdefb33c0f6224e58673d9004f47f7cb3e328b89 # v4.31.10
        if: always()
        with:
          sarif_file: 'trivy-image-vuln-scan-results.sarif'
          category: 'trivy-image-vuln-scan'
